### ISSUE TITLE
Parsing broken when upgrading to Sassdoc 1.8

### ISSUE THREAD

**Issue by alademann** [SassDoc/scss-comment-parser#17]
@FWeinb @HugoGiraudel - when I upgrade to sassdoc `1.8`, I suddenly see the following error that appears to be coming from scss-comment-parser: 

``` bash
[2014-09-30 09:52:27] [ERROR] TypeError: Cannot call method 'trim' of undefined
    at CommentExtractor.parser [as parseContext] (/Users/aaronlademann/workspaces/wf/web-skin/node_modules/sassdoc/node_modules/scss-comment-parser/index.js:128:34)
    at CommentExtractor.extract (/Users/aaronlademann/workspaces/wf/web-skin/node_modules/sassdoc/node_modules/scss-comment-parser/node_modules/cdocparser/index.js:40:23)
    at Parser.parse (/Users/aaronlademann/workspaces/wf/web-skin/node_modules/sassdoc/node_modules/scss-comment-parser/index.js:169:28)
    at Object.Parser.parse (/Users/aaronlademann/workspaces/wf/web-skin/node_modules/sassdoc/src/parser.js:20:34)
    at /Users/aaronlademann/workspaces/wf/web-skin/node_modules/sassdoc/src/file.js:127:27
    at _fulfilled (/Users/aaronlademann/workspaces/wf/web-skin/node_modules/sassdoc/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/aaronlademann/workspaces/wf/web-skin/node_modules/sassdoc/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/aaronlademann/workspaces/wf/web-skin/node_modules/sassdoc/node_modules/q/q.js:749:13)
    at /Users/aaronlademann/workspaces/wf/web-skin/node_modules/sassdoc/node_modules/q/q.js:557:44
    at flush (/Users/aaronlademann/workspaces/wf/web-skin/node_modules/sassdoc/node_modules/q/q.js:108:17)
>> TypeError: Cannot call method 'trim' of undefined
```

It appears that possibly [this commit](https://github.com/SassDoc/scss-comment-parser/commit/2fdc1db528302453e830e1e9f23000b2fccefbf9) by @FWeinb may have changed the regex - which is causing a valid variable to not have a value. ([`match[4]` here](https://github.com/SassDoc/scss-comment-parser/blob/master/index.js#L133)).  

I say this because if I change the regex modified in that commit to 

``` js
var ctxRegEx = /^(@|%|\$)([\w-_]+)*(?:\s+([\w-_]+)|[\s\S]*?\:([\s\S]*?)(?:\s!(\w+))?\;)?/;
```

Everything works - but the result of that commit (which appeared to be a manual merge conflict resolution), was this:

``` js
var ctxRegEx = /^(@|%|\$)([\w-_]+)*(?:\s+([\w-_]+)|[\s\S]*?\:([\s\S]*?)(?:\s!(\w+))?\;\s*(?:\n|$))?/;
```

By my estimation - the line of my SCSS code that is causing `match[4]` to choke is this: 

``` scss
/**
 * Combination of the horizontal and vertical padding values for the badge component when nested within a component's `xs` size variation.
 * ---
 * @type List
 * @since 0.1.2
 * @group core.components.badges
 * ---
 * @requires {variable} $badge-xs-padding-top
 * @requires {variable} $badge-xs-padding-right
 * @requires {variable} $badge-xs-padding-bottom
 * @requires {variable} $badge-xs-padding-left
 */
$badge-xs-padding: $badge-xs-padding-top $badge-xs-padding-right $badge-xs-padding-bottom $badge-xs-padding-left;
```
